CREATE TABLE IF NOT EXISTS `project` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `code` VARCHAR(50) NOT NULL COMMENT '项目编号',
    `name` VARCHAR(200) NOT NULL COMMENT '项目名称',
    `address` VARCHAR(500) NOT NULL COMMENT '地址',
    `budget_amount` DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '预算金额',
    `status` VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT '项目状态：DRAFT草稿、PENDING_START待启动、IN_PROGRESS进行中、PAUSED暂停、DELIVERED已交付、AFTER_SALES售后中、CLOSED已完结、CANCELLED已取消',
    `current_phase` VARCHAR(20) DEFAULT NULL COMMENT '当前主要阶段：PREPARATION筹备、DESIGN设计、CIVIL土建、DECORATION精装、DELIVERY交付、AFTER_SALES售后',
    `health_status` VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT '健康状态：NORMAL正常、WARNING预警、DELAYED滞后、CRITICAL严重异常',
    `pause_reason` VARCHAR(500) DEFAULT NULL COMMENT '暂停原因',
    `cancel_reason` VARCHAR(500) DEFAULT NULL COMMENT '取消原因',
    `planned_start_date` DATE NULL COMMENT '计划开始日期',
    `planned_end_date` DATE NULL COMMENT '计划结束日期',
    `actual_start_date` DATE NULL COMMENT '实际开始日期',
    `actual_end_date` DATE NULL COMMENT '实际结束日期',
    `created_by` BIGINT UNSIGNED NOT NULL COMMENT '创建人',
    `updated_by` BIGINT UNSIGNED NOT NULL COMMENT '修改人',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '项目';

CREATE TABLE IF NOT EXISTS `project_stage` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `project_id` BIGINT UNSIGNED NOT NULL COMMENT '所属项目ID',
    `flow_type` VARCHAR(30) NOT NULL COMMENT'流程类型：DESIGN设计、CIVIL土建、DECORATION精装、DELIVERY交付、AFTER_SALES售后',
    `stage_code` VARCHAR(50) NOT NULL COMMENT '阶段编码',
    `stage_name` VARCHAR(100) NOT NULL COMMENT '阶段名称',
    `sort_order` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序号',
    `status` VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED' COMMENT '状态：NOT_STARTED未开始、IN_PROGRESS进行中、PENDING_ACCEPTANCE待验收、RECTIFYING整改中、COMPLETED已完成、PAUSED暂停、CANCELLED已取消',
    `manager_user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '阶段负责人用户ID',
    `planned_start_date` DATE DEFAULT NULL COMMENT '计划开始日期',
    `planned_end_date` DATE DEFAULT NULL COMMENT '计划完成日期',
    `planned_days` INT UNSIGNED DEFAULT NULL COMMENT '计划工期天数',
    `actual_start_date` DATE DEFAULT NULL COMMENT '实际开始日期',
    `actual_end_date` DATE DEFAULT NULL COMMENT '实际完成日期',
    `progress_percent` DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '完成进度百分比',
    `allow_parallel` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否允许与其他阶段并行',
    `completed_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '完成人用户ID',
    `completed_at` DATETIME DEFAULT NULL COMMENT '完成时间',
    `blocked_reason` VARCHAR(500) DEFAULT NULL COMMENT '阶段阻塞原因',
    `remark` VARCHAR(1000) DEFAULT NULL COMMENT '备注',
    `created_by` BIGINT UNSIGNED NOT NULL COMMENT '创建人',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` BIGINT UNSIGNED NOT NULL COMMENT '修改人',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT='项目阶段';

CREATE TABLE IF NOT EXISTS `project_stage_dependency` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `project_id` BIGINT UNSIGNED NOT NULL COMMENT '项目ID',
    `stage_id` BIGINT UNSIGNED NOT NULL COMMENT '当前阶段ID',
    `predecessor_stage_id` BIGINT UNSIGNED NOT NULL COMMENT '前置阶段ID',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT='项目阶段前置依赖表';

CREATE TABLE IF NOT EXISTS `project_member` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `project_id` BIGINT UNSIGNED NOT NULL COMMENT '项目id',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户id',
    `role_code` VARCHAR(40) NOT NULL COMMENT '项目角色(DESIGNER设计师、ASSISTANT设计助理、CIVIL_PM土建项目经理、DECORATION_PM精装项目经理、CONSTRUCTOR施工员、QC质检员、COST成控人员、FINANCE财务人员、MANAGER老板/管理层、OWNER/业主、OWNER_FAMILY/业主家属)',
    `joined_at` DATETIME NOT NULL COMMENT '加入项目时间',
    `left_at` DATETIME NULL COMMENT '退出项目时间',
    `status`  VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE有效、INACTIVE无效',
    `created_by` BIGINT UNSIGNED NOT NULL COMMENT '创建人',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` BIGINT UNSIGNED NOT NULL COMMENT '修改人',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT='项目成员';

CREATE TABLE IF NOT EXISTS `construction_log` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `project_id` BIGINT UNSIGNED NOT NULL COMMENT '所属项目ID',
    `stage_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '当前项目阶段ID',
    `log_date` DATE NOT NULL COMMENT '日记日期',
    `filled_by` BIGINT UNSIGNED NOT NULL COMMENT '填写人用户ID',
    `log_type` VARCHAR(20) NOT NULL DEFAULT 'DECORATION' COMMENT '日记类型：CIVIL土建、DECORATION精装',
    `weather` VARCHAR(50) DEFAULT NULL COMMENT '今日天气',
    `temperature` VARCHAR(30) DEFAULT NULL COMMENT '今日温度，如20-28℃',
    `trade_progress` JSON NOT NULL COMMENT '各工种今日进展，包含工种、区域、部位、完成情况、遍数、照片等',
    `current_progress_summary` VARCHAR(1000) DEFAULT NULL COMMENT '今日施工总体进展摘要',
    `expected_node_completion_at` DATETIME DEFAULT NULL COMMENT '当前节点预计完成时间',
    `next_day_plan` TEXT NOT NULL COMMENT '明日或下一步工作计划',
    `next_day_trade_plan` JSON DEFAULT NULL COMMENT '明日工种安排',
    `site_issues` JSON DEFAULT NULL COMMENT '现场问题记录，包含问题描述、照片、责任人、整改期限、问题单ID',
    `has_issue` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否存在现场问题：0否、1是',
    `owner_mentions` JSON DEFAULT NULL COMMENT '需要业主配合或确认的事项',
    `qc_mentions` JSON DEFAULT NULL COMMENT '需要质检员处理或验收的事项',
    `status` VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT草稿、SUBMITTED已提交、LOCKED已锁定',
    `submitted_at` DATETIME DEFAULT NULL COMMENT '提交时间',
    `locked_at` DATETIME DEFAULT NULL COMMENT '锁定时间',
    `remark` VARCHAR(1000) DEFAULT NULL COMMENT '其他备注',
    `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT='施工日志';

CREATE TABLE IF NOT EXISTS `inspection` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `project_id` BIGINT UNSIGNED NOT NULL COMMENT '项目id',
    `stage_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '当前项目阶段ID',
    `inspection_name` VARCHAR(100) NOT NULL COMMENT '验收名称',
    `parent_inspection_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '原验收单ID，复验时关联上一轮验收单',
    `inspection_round` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '验收轮次：1首次验收，2第一次复验，以此类推',
    `inspection_date` DATE NOT NULL COMMENT '验收日期',
    `inspection_started_at` DATETIME DEFAULT NULL COMMENT '验收开始时间',
    `inspection_finished_at` DATETIME DEFAULT NULL COMMENT '验收结束时间',
    `qc_user_id` BIGINT UNSIGNED NOT NULL COMMENT '质检员用户ID',
    `project_manager_user_id` BIGINT UNSIGNED NOT NULL COMMENT '项目经理用户ID',
    `participants` JSON DEFAULT NULL COMMENT '参与人员，格式为用户ID、姓名、角色等',
    `check_items` JSON NOT NULL COMMENT '验收检查项，包含检查内容、检查结果、备注、照片等',
    `site_photos` JSON NOT NULL COMMENT '验收现场总体照片，必须上传',
    `conclusion` VARCHAR(30) DEFAULT NULL COMMENT '验收结论：PASSED通过、RECTIFICATION_REQUIRED整改后复验、FAILED不通过',
    `issue_ticket_ids` JSON DEFAULT NULL COMMENT '本次验收生成的问题单ID集合',
    `issue_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '问题总数',
    `open_issue_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '未关闭问题数',
    `rectification_deadline` DATETIME DEFAULT NULL COMMENT '整改截止时间',
    `signatures` JSON DEFAULT NULL COMMENT '签字信息，包含签字人、角色、签字文件、签字时间',
    `qc_signed_at` DATETIME DEFAULT NULL COMMENT '质检员签字时间',
    `pm_signed_at` DATETIME DEFAULT NULL COMMENT '项目经理签字时间',
    `owner_signed_at` DATETIME DEFAULT NULL COMMENT '业主签字时间',
    `status` VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT '验收单状态：DRAFT草稿、SUBMITTED已提交、PENDING_SIGNATURE待签字、PENDING_RECTIFICATION待整改、PENDING_REINSPECTION待复验、PASSED已通过、FAILED未通过、VOID已作废',
    `passed_at` DATETIME DEFAULT NULL COMMENT '验收通过时间',
    `remark` VARCHAR(1000) DEFAULT NULL COMMENT '备注',
    `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT='验收单';

CREATE TABLE IF NOT EXISTS `issue_ticket` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `code` VARCHAR(50) NOT NULL COMMENT '编号',
    `project_id` BIGINT UNSIGNED NOT NULL COMMENT '所属项目ID',
    `stage_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '关联项目阶段ID',
    `inspection_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '关联验收单ID',
    `daily_log_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '关联施工日记ID',
    `source_type` VARCHAR(30) NOT NULL DEFAULT 'MANUAL' COMMENT '问题来源：MANUAL手动创建、DAILY_LOG施工日记、INSPECTION验收发现、OWNER_FEEDBACK业主反馈、AFTER_SALES售后报修',
    `issue_type` VARCHAR(30) NOT NULL DEFAULT 'QUALITY' COMMENT '问题类型：QUALITY质量问题、PROGRESS进度问题、SAFETY安全问题、MATERIAL材料问题、DESIGN设计问题、SERVICE服务问题、OTHER其他问题',
    `title` VARCHAR(200) NOT NULL COMMENT '问题标题',
    `description` TEXT NOT NULL COMMENT '问题详细描述',
    `severity` VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' COMMENT '严重程度：LOW一般、MEDIUM中等、HIGH严重、CRITICAL紧急',
    `issue_photos` JSON NOT NULL COMMENT '问题现场照片，JSON数组',
    `reported_by` BIGINT UNSIGNED NOT NULL COMMENT '问题发现人用户ID',
    `reported_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '问题发现时间',
    `responsible_user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '整改责任人用户ID',
    `assigned_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '分配人用户ID',
    `assigned_at` DATETIME DEFAULT NULL COMMENT '分配时间',
    `rectification_deadline` DATETIME DEFAULT NULL COMMENT '整改截止时间',
    `status` VARCHAR(30) NOT NULL DEFAULT 'OPEN' COMMENT '问题状态：OPEN待分配、ASSIGNED已分配、RECTIFYING整改中、PENDING_REVIEW待复验、REJECTED复验不通过、CLOSED已关闭、CANCELLED已取消',
    `rectification_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '整改提交次数',
    `rectification_description` TEXT DEFAULT NULL COMMENT '最新整改说明',
    `rectification_photos` JSON DEFAULT NULL COMMENT '最新整改完成照片，JSON数组',
    `rectification_submitted_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '整改提交人用户ID',
    `rectification_submitted_at` DATETIME DEFAULT NULL COMMENT '整改提交时间',
    `review_user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '复验人或质检员用户ID',
    `review_result` VARCHAR(20) DEFAULT NULL COMMENT '复验结果：PASSED通过、REJECTED不通过',
    `review_remark` VARCHAR(1000) DEFAULT NULL COMMENT '复验说明',
    `review_photos` JSON DEFAULT NULL COMMENT '复验现场照片，JSON数组',
    `reviewed_at` DATETIME DEFAULT NULL COMMENT '复验时间',
    `closed_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '关闭人用户ID',
    `closed_at` DATETIME DEFAULT NULL COMMENT '问题关闭时间',
    `cancel_reason` VARCHAR(500) DEFAULT NULL COMMENT '取消原因',
    `remark` VARCHAR(1000) DEFAULT NULL COMMENT '其他备注',
    `created_by` BIGINT UNSIGNED NOT NULL COMMENT '创建人',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT='问题单';

CREATE TABLE IF NOT EXISTS `payment_request` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `project_id` BIGINT UNSIGNED NOT NULL COMMENT '所属项目ID',
    `company_id` BIGINT UNSIGNED NOT NULL COMMENT '公司id',
    `applicant_id` BIGINT UNSIGNED NOT NULL COMMENT '申请人id',
    `amount` DECIMAL(18,2) NOT NULL COMMENT '金额',
    `description` TEXT COMMENT '描述',
    `attachments` JSON COMMENT '合同、发票、送货单',
    `status` INT UNSIGNED DEFAULT 0 COMMENT '状态(0:草稿;1:审批中;2:已撤销;3:已通过;4:已驳回;)',
    `submit_time` DATETIME DEFAULT NULL COMMENT '提交时间',
	`created_by` BIGINT UNSIGNED NOT NULL COMMENT '创建人',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT='请款单';

CREATE TABLE IF NOT EXISTS `contract`  (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `project_id` BIGINT UNSIGNED NOT NULL COMMENT '所属项目ID',
    `contract_type` VARCHAR(30) NOT NULL COMMENT '合同类型：TEAM班组合同、SUPPLIER供应商合同、DESIGN设计合同、CUSTOMER客户合同、OTHER其他合同',
    `contract_code` VARCHAR(50) NOT NULL COMMENT '合同编号',
    `contract_name` VARCHAR(200) NOT NULL COMMENT '合同名称',
    `contract_files` JSON NOT NULL COMMENT '合同附件，包含PDF、图片、扫描件等',
    `created_by` BIGINT UNSIGNED NOT NULL COMMENT '创建人',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT='合同';

CREATE TABLE IF NOT EXISTS `material_arrival` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `project_id` BIGINT UNSIGNED NOT NULL COMMENT '所属项目ID',
    `arrival_at` DATETIME NOT NULL COMMENT '到达时间',
    `files` JSON NOT NULL COMMENT '相关附件',
    `created_by` BIGINT UNSIGNED NOT NULL COMMENT '创建人',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT='材料到场记录';

CREATE TABLE IF NOT EXISTS `project_handover` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `handover_code` VARCHAR(50) NOT NULL COMMENT '交接单编号',
    `project_id` BIGINT UNSIGNED NOT NULL COMMENT '所属项目ID',
    `handover_type` VARCHAR(40) NOT NULL COMMENT '交接类型：DESIGN_TO_CIVIL设计交接土建、DESIGN_TO_DECORATION设计交接精装、CIVIL_TO_DECORATION土建交接精装、OTHER其他交接',
    `handover_name` VARCHAR(200) NOT NULL COMMENT '交接单名称',
    `from_stage_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '移交来源阶段ID',
    `to_stage_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '接收目标阶段ID',
    `from_flow_type` VARCHAR(30) NOT NULL COMMENT '移交流程：DESIGN设计、CIVIL土建、DECORATION精装',
    `to_flow_type` VARCHAR(30) NOT NULL COMMENT '接收流程：CIVIL土建、DECORATION精装',
    `related_inspection_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '关联验收单ID，例如主体结构验收单',
    `handover_date` DATE DEFAULT NULL COMMENT '实际交接日期',
    `handover_user_id` BIGINT UNSIGNED NOT NULL COMMENT '移交负责人用户ID',
    `receiver_user_id` BIGINT UNSIGNED NOT NULL COMMENT '接收负责人用户ID',
    `handover_items` JSON NOT NULL COMMENT '交接检查项，包含交接内容、数量、状态、备注、照片等',
    `document_files` JSON DEFAULT NULL COMMENT '移交资料附件，如图纸、报告、清单、现场照片',
    `unfinished_items` JSON DEFAULT NULL COMMENT '遗留事项及处理计划',
    `open_issue_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '未关闭问题数量',
    `handover_conclusion` VARCHAR(30) DEFAULT NULL COMMENT '交接结论：ACCEPTED接收通过、CONDITIONAL_ACCEPTANCE有条件接收、REJECTED拒绝接收',
    `handover_remark` VARCHAR(1000) DEFAULT NULL COMMENT '移交方说明',
    `receiver_remark` VARCHAR(1000) DEFAULT NULL COMMENT '接收方意见',
    `handover_signature_file_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '移交方签字文件ID',
    `receiver_signature_file_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '接收方签字文件ID',
    `handover_signed_at` DATETIME DEFAULT NULL COMMENT '移交方签字时间',
    `receiver_signed_at` DATETIME DEFAULT NULL COMMENT '接收方签字时间',
    `status` VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT草稿、PENDING_HANDOVER待移交、PENDING_RECEIVE待接收、REJECTED已退回、COMPLETED已完成、CANCELLED已取消',
    `completed_at` DATETIME DEFAULT NULL COMMENT '交接完成时间',
    `cancel_reason` VARCHAR(500) DEFAULT NULL COMMENT '取消原因',
    `created_by` BIGINT UNSIGNED NOT NULL COMMENT '创建人',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT='交接单';

CREATE TABLE IF NOT EXISTS `notification` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `project_id` BIGINT UNSIGNED NOT NULL COMMENT '所属项目ID',
    `sender_user_id` BIGINT UNSIGNED NOT NULL COMMENT '发送人用户ID',
    `recipient_user_id` BIGINT UNSIGNED NOT NULL COMMENT '接收人用户ID',
    `type` VARCHAR(20) NOT NULL DEFAULT 'NOTICE' COMMENT '消息类型：AI提醒、管家提醒、节点逾期、请款审批',
    `title` VARCHAR(200) NOT NULL COMMENT '消息标题',
    `content` TEXT NOT NULL COMMENT '消息内容',
    `status` VARCHAR(20) NOT NULL DEFAULT 'UNREAD' COMMENT '阅读状态：UNREAD未读、READ已读',
    `created_by` BIGINT UNSIGNED NOT NULL COMMENT '创建人',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '修改人',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT='提醒/通知';
